[env:esp32-s3-devkitc-1]
platform = espressif32 @ 6.4.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
debug_tool = esp-builtin
upload_protocol = esp-builtin
debug_build_flags = -O0 -ggdb3 -g3
debug_init_break = tbreak setup 
build_type = debug
; N16R8 Altın Ayarları (JSON'dan gelen)
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
lib_ldf_mode = deep+
lib_deps =
    bakercp/CRC32 @2.0.0
    WiFi
    WiFiClientSecure
    links2004/WebSockets @ ^2.4.1
    bblanchon/ArduinoJson @ ^7.4.3

; Yolları (Path) BURAYA, build_flags altına taşıdık:
build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_ESP32S3_DEV=1
    -I"C:/Users/husey/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src"
    -I"C:/Users/husey/.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src"
