[env:esp32-s3-devkitc-1]
platform = espressif32 @ 6.6.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; En güvenli mod: Her şeyi 4-bit (Quad) yapıyoruz. 
; N16R8 ise bile bu modda mutlaka çalışır.
board_build.arduino.memory_type = qio_qio
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 16MB

build_flags = 
    -DBOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -I"C:/Users/husey/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src"
    -I"C:/Users/husey/.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src"




  