[platformio]
default_envs = esp32-s3-devkitc1-n16r8

[env:esp32-s3-devkitc1-n16r8]
board = esp32-s3-devkitc1-n16r8
platform = espressif32
framework = arduino

lib_ldf_mode = deep+
lib_deps =
	PubSubClient
    adafruit/Adafruit NeoPixel
    bakercp/CRC32 @ 2.0.0
    links2004/WebSockets @ ^2.4.1
    bblanchon/ArduinoJson @ ^7.4.3

build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -I"C:/Users/husey/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src"
    -I"C:/Users/husey/.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src"
upload_speed = 921600
